package com.criccast.beans;

// Generated May 20, 2014 1:17:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Matches generated by hbm2java
 */
@Entity
@Table(name = "matches", catalog = "criccast")
public class Matches implements java.io.Serializable {

	private int id;
	private String name;
	private String team1id;
	private String team2id;
	private Date date;
	private Integer locationid;
	private Integer tournmentId;
	private Integer noOfOvers;
	private String matchescol;

	public Matches() {
	}

	public Matches(int id) {
		this.id = id;
	}

	public Matches(int id, String name, String team1id, String team2id,
			Date date, Integer locationid, Integer tournmentId,
			Integer noOfOvers, String matchescol) {
		this.id = id;
		this.name = name;
		this.team1id = team1id;
		this.team2id = team2id;
		this.date = date;
		this.locationid = locationid;
		this.tournmentId = tournmentId;
		this.noOfOvers = noOfOvers;
		this.matchescol = matchescol;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "team1id", length = 45)
	public String getTeam1id() {
		return this.team1id;
	}

	public void setTeam1id(String team1id) {
		this.team1id = team1id;
	}

	@Column(name = "team2id", length = 45)
	public String getTeam2id() {
		return this.team2id;
	}

	public void setTeam2id(String team2id) {
		this.team2id = team2id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "locationid")
	public Integer getLocationid() {
		return this.locationid;
	}

	public void setLocationid(Integer locationid) {
		this.locationid = locationid;
	}

	@Column(name = "tournmentID")
	public Integer getTournmentId() {
		return this.tournmentId;
	}

	public void setTournmentId(Integer tournmentId) {
		this.tournmentId = tournmentId;
	}

	@Column(name = "noOfOvers")
	public Integer getNoOfOvers() {
		return this.noOfOvers;
	}

	public void setNoOfOvers(Integer noOfOvers) {
		this.noOfOvers = noOfOvers;
	}

	@Column(name = "Matchescol", length = 45)
	public String getMatchescol() {
		return this.matchescol;
	}

	public void setMatchescol(String matchescol) {
		this.matchescol = matchescol;
	}

}
