package com.criccast.beans;

// Generated May 20, 2014 1:17:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Over generated by hbm2java
 */
@Entity
@Table(name = "over", catalog = "criccast")
public class Over implements java.io.Serializable {

	private int id;
	private String matchId;
	private String teamId;
	private String overcol;

	public Over() {
	}

	public Over(int id) {
		this.id = id;
	}

	public Over(int id, String matchId, String teamId, String overcol) {
		this.id = id;
		this.matchId = matchId;
		this.teamId = teamId;
		this.overcol = overcol;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "matchID", length = 45)
	public String getMatchId() {
		return this.matchId;
	}

	public void setMatchId(String matchId) {
		this.matchId = matchId;
	}

	@Column(name = "teamID", length = 45)
	public String getTeamId() {
		return this.teamId;
	}

	public void setTeamId(String teamId) {
		this.teamId = teamId;
	}

	@Column(name = "Overcol", length = 45)
	public String getOvercol() {
		return this.overcol;
	}

	public void setOvercol(String overcol) {
		this.overcol = overcol;
	}

}
