package com.criccast.beans;

// Generated May 20, 2014 1:17:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Scores generated by hbm2java
 */
@Entity
@Table(name = "scores", catalog = "criccast")
public class Scores implements java.io.Serializable {

	private int id;
	private String matchId;
	private String teamId;
	private String playerId;
	private String ballCount;
	private String score;

	public Scores() {
	}

	public Scores(int id) {
		this.id = id;
	}

	public Scores(int id, String matchId, String teamId, String playerId,
			String ballCount, String score) {
		this.id = id;
		this.matchId = matchId;
		this.teamId = teamId;
		this.playerId = playerId;
		this.ballCount = ballCount;
		this.score = score;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "matchID", length = 45)
	public String getMatchId() {
		return this.matchId;
	}

	public void setMatchId(String matchId) {
		this.matchId = matchId;
	}

	@Column(name = "teamID", length = 45)
	public String getTeamId() {
		return this.teamId;
	}

	public void setTeamId(String teamId) {
		this.teamId = teamId;
	}

	@Column(name = "playerID", length = 45)
	public String getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(String playerId) {
		this.playerId = playerId;
	}

	@Column(name = "ballCount", length = 45)
	public String getBallCount() {
		return this.ballCount;
	}

	public void setBallCount(String ballCount) {
		this.ballCount = ballCount;
	}

	@Column(name = "score", length = 45)
	public String getScore() {
		return this.score;
	}

	public void setScore(String score) {
		this.score = score;
	}

}
