package com.criccast.beans;

// Generated May 20, 2014 1:17:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Team generated by hbm2java
 */
@Entity
@Table(name = "team", catalog = "criccast")
public class Team implements java.io.Serializable {

	private int id;
	private String name;
	private String noOfPlayers;

	public Team() {
	}

	public Team(int id) {
		this.id = id;
	}

	public Team(int id, String name, String noOfPlayers) {
		this.id = id;
		this.name = name;
		this.noOfPlayers = noOfPlayers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "noOfPlayers", length = 45)
	public String getNoOfPlayers() {
		return this.noOfPlayers;
	}

	public void setNoOfPlayers(String noOfPlayers) {
		this.noOfPlayers = noOfPlayers;
	}

}
